name: Update Metal Rates

on:
  workflow_dispatch:

  schedule:
    - cron: '*/15 * * * *'

jobs:

  update-metal-rates:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run Script
        env:
          FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
        run: python main.py
